const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const context=vm.createContext({Component:class{},KanbanController:class{},standardFieldProps:{},kanbanView:{Renderer:class{}},registry:{category:()=>({add(){}})}});
vm.runInContext(fs.readFileSync(path.join(__dirname,'../static/src/js/production_pipeline.js'),'utf8').replace(/^import .*;$/gm,'').replace(/export /g,'')+'\nthis.api={groupIdenticalPieces,GroupedPieceRenderer,ProductionPieceSelector,ProductionPieceTitle};',context);
const {groupIdenticalPieces:group,GroupedPieceRenderer:Renderer,ProductionPieceSelector:Selector}=context.api;
const record=(id,key='same',extra={})=>({id:'r'+id,resId:id,selected:false,data:{state:'draft',route_graph:{display_group_key:key},...extra},async toggleSelection(v){this.selected=v;}});
const records=[record(1),record(2),record(3,'different'),record(4,'same',{is_custom:true}),record(5,'same',{state:'approved'}),record(6,null),record(7,null)];
assert.deepEqual(Array.from(group(records),g=>g.records.length),[2,1,1,1,1,1]);
assert.equal(group(records)[0].records[0],records[0]);
const r=Object.create(Renderer.prototype);
r.props={list:{records,isGrouped:false},openRecord:rec=>rec.resId};
r.pieceGroups={expanded:{}};
assert.equal(r.getGroupsOrRecords().length,6);
assert.equal(r.displayGroup(records[0]).length,2);
assert.equal(r.displayGroup({...records[0]}).length,2,'OWL proxies may differ, match native resId');
const title=Object.create(context.api.ProductionPieceTitle.prototype);
title.props={record:{...records[0]}}; title.env={ntpDisplayGroup:rec=>r.displayGroup(rec)};
assert.equal(title.count,2,'Title quantity matches the whole group');
assert.equal(r.expandForEdit(records[0]),true);
assert.equal(title.count,1,'Expanded title describes an individual');
assert.equal(r.getGroupsOrRecords().length,7);
assert.equal(r.displayGroup(records[0]).length,1);
assert.equal(r.openPieceRecord(records[0]),1);
r.togglePieceGroup('same:same');
const s=Object.create(Selector.prototype);s.props={record:records[0]};s.env={ntpDisplayGroup:rec=>r.displayGroup(rec)};
s.reactiveBulk={canApprove:true,busy:false,confirming:false};
(async()=>{
 await s.onChange({target:{checked:true}});
 assert(records[0].selected && records[1].selected && !records[2].selected);
 assert.equal(s.allSelected,true);
 records[1].selected=false;assert.equal(s.allSelected,false);
 s.reactiveBulk.confirming=true;await s.onChange({target:{checked:false}});assert(records[0].selected);
 r.props.list.records=[record(8,'other')];assert.equal(r.getGroupsOrRecords().length,1);
 console.log('PASS identical grouping, customized/state isolation, original records, group selection, dialog guard, safe edit expansion and navigation');
})().catch(e=>{console.error(e);process.exit(1)});
