const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const read = name => fs.readFileSync(path.join(__dirname, '..', name), 'utf8');
const source = read('static/src/js/production_pipeline.js');
const template = read('static/src/xml/production_pipeline.xml');
const views = read('views/production_plan_views.xml');
const badge = template.match(/<t t-name="furniture_need_to_produce.PieceCustom">([\s\S]*?)<\/t>/)[1];
assert.match(badge, /t-if="props.record.data.custom_bom_modified"/);
assert.match(badge, /<span[^>]*class="o_ntp_custom_badge"/);
assert.doesNotMatch(badge, /<button|t-on-|tabindex|role="button"/);
assert.doesNotMatch(source, /"action_toggle_custom"/);
assert.doesNotMatch(views, /name="action_approve"|name="action_toggle_custom"/);
assert.match(views, /widget="need_produce_selector"/);
assert.doesNotMatch(template, /o_ntp_approve_selected|o_ntp_workspace_approve_product|o_ntp_workspace_product_select/);
assert.equal((template.match(/t-on-click="[^"\n]*approveWorkspace/g) || []).length, 1);
assert.match(template, /t-on-click="approveWorkspaceScope"/);
assert.match(template, /t-esc="workspaceApprovalLabel"/);
assert.match(template, /o_ntp_bulk_toolbar/);
assert.match(template, /t-esc="workspaceSelectedPieces.length"/);
assert.match(template, /o_ntp_workspace_approve_scope/);
assert.match(views, /<span t-if="record.custom_bom_modified.raw_value" class="o_ntp_custom_badge"/);
console.log('PASS: single top-scope approval; no per-piece/selected approval or manual Custom; BoM-only read-only badge');
