const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname, '../static/src/js/production_route_graph.js'), 'utf8');
const component = source.slice(source.indexOf('let graphSequence = 0;'), source.indexOf('registry.category("fields")'));
const context = vm.createContext({Component: class {}, standardFieldProps: {}});
vm.runInContext(component.replace('export class ', 'class ') + '\nglobalThis.Graph=NeedProduceGraphField;', context);
const graph = new context.Graph();
assert.equal(graph.icon({kind: 'incoming'}), 'fa-hourglass-half');
assert.equal(graph.icon({kind: 'stock'}), 'fa-check-circle');
assert.equal(graph.icon({kind: 'incoming', withdrawn: true}), 'fa-check');
assert.notEqual(graph.icon({kind: 'stage', stage_code: 'upholstery'}), 'fa-hourglass-half');
const incoming = {kind: 'incoming', label: 'الكسوة', production_name: 'MRP/2026/08026'};
assert.equal(graph.nodeDescription(incoming), 'الكسوة — ينتظر أمرًا قائمًا — مدة الانتظار غير محددة — MRP/2026/08026');
assert.match(graph.nodeDescription({kind: 'history', label: 'التفصيل', quantity: 3}), /محجوز — لم يُسحب بعد — كمية الدفعة 3/);
assert.equal(graph.nodeDescription({kind: 'stage', label: 'التغليف'}), 'التغليف');
const template = fs.readFileSync(path.join(__dirname, '../static/src/xml/production_route_graph.xml'), 'utf8');
assert(template.includes('t-att-title="nodeDescription(node)"'));
assert(template.includes('t-att-aria-label="nodeDescription(node)"'));
assert(template.includes('t-esc="node.production_name'));
const cardTemplate = template.slice(template.indexOf('<article '), template.indexOf('</article>'));
assert(!cardTemplate.includes('ينتظر أمرًا قائمًا'), 'Waiting text must be absent from the card template, not just CSS-hidden');
assert(cardTemplate.includes('t-if="node.kind !== \'incoming\' or node.withdrawn" class="o_ntp_graph_node_kind"'));
assert(template.includes('o_ntp_graph_dot_incoming"/> ينتظر أمرًا قائمًا'), 'Keep the graph legend unchanged');
const css = fs.readFileSync(path.join(__dirname, '../static/src/css/production_route_graph.css'), 'utf8');
const selector = '.o_ntp_graph_node_incoming:not(.is-withdrawn) .o_ntp_graph_node_icon > .fa-hourglass-half';
assert(css.includes(selector + ' {\n    display: inline-block;'));
assert(css.includes('animation: ntp-wait-hourglass 2.4s ease-in-out infinite;'));
assert(css.includes('@keyframes ntp-wait-hourglass'));
assert(css.slice(css.indexOf('@media (prefers-reduced-motion: reduce)')).includes(selector + ' { animation: none; }'));
console.log('PASS: waiting-hourglass animation scoped to incoming nodes, stock/stage icons unchanged, reduced motion supported');
