{
    'name': 'طلبات التسليم',
    'version': '18.0.1.12.9',
    'summary': 'Administrator delivery requests connected to MRP II and finished stock',
    'category': 'Manufacturing',
    'license': 'LGPL-3',
    'depends': ['furniture_mrp', 'mapilla_backend_theme'],
    'data': [
        'security/delivery_security.xml',
        'security/ir.model.access.csv',
        'views/delivery_stage_warning_view.xml',
        'views/delivery_menus.xml',
        'views/delivery_design.xml',
        'views/delivery_specifications.xml',
        'views/customer_specifications.xml',
        'views/delivery_creation_wizard.xml',
        'views/delivery_queue.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'furniture_delivery_requests/static/src/css/delivery_requests.css',
            'furniture_delivery_requests/static/src/xml/delivery_navigation.xml',
            'furniture_delivery_requests/static/src/xml/delivery_list.xml',
            'furniture_delivery_requests/static/src/scss/delivery_list.scss',
            'furniture_delivery_requests/static/src/js/delivery_product_picker.js',
            'furniture_delivery_requests/static/src/xml/delivery_product_picker.xml',
            'furniture_delivery_requests/static/src/scss/delivery_design.scss',
            'furniture_delivery_requests/static/src/scss/delivery_creation.scss',
            'furniture_delivery_requests/static/src/js/delivery_creation.js',
            'furniture_delivery_requests/static/src/js/delivery_specifications.js',
            'furniture_delivery_requests/static/src/xml/delivery_specifications.xml',
            'furniture_delivery_requests/static/src/js/delivery_edit_lines.js',
        ],
    },
    'pre_init_hook': 'pre_init_hook',
    'uninstall_hook': 'uninstall_hook',
    'application': True,
    'installable': True,
    'auto_install': False,
}
