{
    'name': 'النواقص',
    'version': '18.0.1.0.19',
    'category': 'Manufacturing',
    'icon': '/furniture_need_to_produce/static/description/icon.svg',
    'summary': 'Stock-aware piece approval with a single-receipt parallel bases/finishing cycle',
    'license': 'LGPL-3',
    'depends': ['furniture_stage_replenishment'],
    'data': ['security/security.xml', 'security/ir.model.access.csv', 'views/production_plan_views.xml',
             'views/stage_shortages_views.xml', 'views/approved_tracking_views.xml', 'views/demand_cycle_views.xml'],
    'assets': {'web.assets_backend': [
        'furniture_need_to_produce/static/src/js/approved_tracking.js',
        'furniture_need_to_produce/static/src/xml/approved_tracking.xml',
        'furniture_need_to_produce/static/src/css/approved_tracking.css',
        'furniture_need_to_produce/static/src/js/supervisor_completed.js',
        'furniture_need_to_produce/static/src/js/textile_kits.js',
        'furniture_need_to_produce/static/src/xml/supervisor_completed.xml',
        'furniture_need_to_produce/static/src/css/supervisor_completed.css',
        'furniture_need_to_produce/static/src/js/stage_shortages.js',
        'furniture_need_to_produce/static/src/js/minmax_workspace.js',
        'furniture_need_to_produce/static/src/xml/minmax_workspace.xml',
        'furniture_need_to_produce/static/src/css/minmax_workspace.css',
        'furniture_need_to_produce/static/src/js/need_produce_list.js',
        'furniture_need_to_produce/static/src/xml/need_produce_list.xml',
        'furniture_need_to_produce/static/src/css/need_produce_list.css',
        'furniture_need_to_produce/static/src/js/production_route_graph.js',
        'furniture_need_to_produce/static/src/xml/production_route_graph.xml',
        'furniture_need_to_produce/static/src/css/production_route_graph.css',
        'furniture_need_to_produce/static/src/js/production_pipeline.js',
        'furniture_need_to_produce/static/src/xml/production_pipeline.xml',
        'furniture_need_to_produce/static/src/css/production_pipeline.css',
        'furniture_need_to_produce/static/src/css/stage_shortages.css',
        'furniture_need_to_produce/static/src/js/piece_partners.js',
        'furniture_need_to_produce/static/src/xml/piece_partners.xml',
    ]},
    'installable': True,
    'application': True,
}
