# -*- coding: utf-8 -*-
{
    'name': 'MRP II',
    'version': '18.0.2.2.389',
    'summary': 'إنتاج أثاث بتحويلات FIFO بين أوامر المراحل وتغليف نهائي آلي',
    'description': """
        نظام متكامل لإدارة إنتاج مصنع الأثاث (انتريهات 4 قطع / طقم) يشمل:
        - المرحلة 1: التقديم
        - المرحلة 2: تصنيع دهانات
        - المرحلة 3: تجميع
        - المرحلة 4: القواعد
        - المرحلة 5: تجهيز
        - المرحلة 6: كسوه
        - المرحلة 7: تفصيل (تفصيل + خياطة + تكاوي)
        - المرحلة 8: التغليف
        - ربط قائمة المواد (BoM) واستهلاك المخزون
        - توليد طلبات الشراء للمواد الناقصة
        - تتبع WIP (صالة التصنيع)
        - توزيع التكاليف من 3 مصادر: مواد + عمالة + Overhead
        - جدول الإنتاج الرئيسي (MPS) مع طاقة 8 أقسام
    """,
    'category': 'Manufacturing',
    'author': 'Custom Development',
    'license': 'LGPL-3',
    'depends': [
        'base', 'mail', 'product', 'stock', 'mrp', 'hr', 'hr_attendance', 'hr_contract',
        'purchase', 'analytic', 'account', 'stock_account', 'sale_mrp', 'sale_management',
        'simple_payroll_salary-2', 'factory_payroll', 'whatsapp_integration',
    ],
    'data': [
        # Security
        'security/furniture_mrp_security.xml',
        'security/ir.model.access.csv',
        'security/furniture_payroll_security.xml',
        'security/furniture_mrp_operational_scope_rules.xml',
        'security/stage_visibility_rules.xml',
        'security/furniture_mrp_future_order_rules.xml',
        # Data
        'data/mrp_sequence_data.xml',
        'data/mrp_workcenter_data.xml',
        'data/mrp_stage_location_data.xml',
        'data/mrp_employee_stage_data.xml',
        'data/mrp_supervisor_stage_group_sync.xml',
        'data/mrp_mps_schedule_data.xml',
        'data/furniture_uom_data.xml',
        # Views
        'views/product_template_view.xml',
        'views/stock_compact_numbers_view.xml',
        'views/product_classification_view.xml',
        'views/hr_employee_view.xml',
        'views/hr_employee_pay_report_view.xml',
        'views/simple_payroll_slip_view.xml',
        'views/payroll_slip_wizard_view.xml',
        'views/payroll_batch_wizard_view.xml',
        'views/payroll_payment_wizard_view.xml',
        'views/payroll_whatsapp_wizard_view.xml',
        'views/account_move_view.xml',
        'views/stock_picking_view.xml',
        'views/sale_kit_allocation_view.xml',
        'views/purchase_order_view.xml',
        'views/mrp_bom_view.xml',
        'views/mrp_stage_transfer_wizard_view.xml',
        'views/mrp_finished_transfer_wizard_view.xml',
        'views/mrp_start_stage_wizard_view.xml',
        'views/mrp_first_stage_start_wizard_view.xml',
        'views/mrp_empty_confirm_wizard_view.xml',
        'views/mrp_stage_quality_send_wizard_view.xml',
        'views/mrp_stage_start_carryover_wizard_view.xml',
        'views/mrp_stage_material_preview_wizard_view.xml',
        'views/mrp_stage_product_batch_bom_wizard_view.xml',
        'views/mrp_store_request_view.xml',
        'views/mrp_production_line_stage_wizard_view.xml',
        'views/mrp_product_stage_progress_view.xml',
        'views/mrp_batch_launcher_action.xml',
        'views/mrp_production_line_bom_popup_view.xml',
        'views/mrp_tailoring_material_setup_view.xml',
        'views/mrp_material_check_batch_wizard_view.xml',
        'views/mrp_production_stage_warning_view.xml',
        'views/mrp_production_view.xml',
        'views/mrp_production_quick_add_wizard_view.xml',
        'views/mrp_priming_view.xml',
        'views/mrp_painting_view.xml',
        'views/mrp_carpentry_view.xml',
        'views/mrp_bases_view.xml',
        'views/mrp_upholstery_view.xml',
        'views/mrp_packaging_view.xml',
        'views/mrp_finishing_view.xml',
        'views/mrp_tailoring_view.xml',
        'views/mrp_stage_cost_view.xml',
        'views/mrp_costing_view.xml',
        'views/mrp_mps_view.xml',
        'views/mrp_mps_schedule_view.xml',
        'views/mrp_dashboard_view.xml',
        'views/future_delivery_order_view.xml',
        'views/mrp_location_view.xml',
        'views/stock_inventory_overview_view.xml',
        'views/mrp_completion_view.xml',
        'views/mrp_menu.xml',
        'views/mrp_advance_material_release_view.xml',
        # Reports
        'report/report_brand_header.xml',
        'report/mrp_production_report.xml',
        'report/mrp_production_report_template.xml',
        'report/mrp_department_reports.xml',
        'report/mrp_department_report_templates.xml',
        'report/mrp_cost_report.xml',
        'report/mrp_cost_report_template.xml',
        'report/mrp_stage_cost_report.xml',
        'report/mrp_stage_cost_report_template.xml',
        'report/mrp_warehouse_receipt_report.xml',
        'report/mrp_warehouse_receipt_report_template.xml',
        'report/furniture_payroll_slip_report.xml',
        'report/furniture_payroll_batch_report.xml',
        'views/furniture_payroll_menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'furniture_mrp/static/src/css/furniture_mrp.css',
            'furniture_mrp/static/src/js/payroll_period_list.js',
            'furniture_mrp/static/src/xml/payroll_period_list.xml',
            'furniture_mrp/static/src/css/mrp_stage_dashboard.css',
            'furniture_mrp/static/src/css/mrp_completion.css',
            'furniture_mrp/static/src/js/tailoring_setup_inline_form.js',
            'furniture_mrp/static/src/js/bom_source_autocopy.js',
            'furniture_mrp/static/src/js/compact_quantity.js',
            'furniture_mrp/static/src/js/furniture_model_navigator.js',
            'furniture_mrp/static/src/xml/furniture_model_navigator.xml',
            'furniture_mrp/static/src/js/furniture_quick_card_selector.js',
            'furniture_mrp/static/src/xml/furniture_quick_card_selector.xml',
            'furniture_mrp/static/src/js/furniture_stage_selector.js',
            'furniture_mrp/static/src/xml/furniture_stage_selector.xml',
            'furniture_mrp/static/src/js/store_request_notification_service.js',
            'furniture_mrp/static/src/js/future_order_systray.js',
            'furniture_mrp/static/src/xml/future_order_systray.xml',
            'furniture_mrp/static/src/css/future_order.css',
            'furniture_mrp/static/src/js/inventory_overview_locations.js',
            'furniture_mrp/static/src/xml/inventory_overview_locations.xml',
            'furniture_mrp/static/src/css/inventory_overview_locations.css',
            'furniture_mrp/static/src/js/mrp_stage_control_panel.js',
            'furniture_mrp/static/src/xml/mrp_stage_control_panel.xml',
            'furniture_mrp/static/src/js/mrp_stage_dashboard.js',
            'furniture_mrp/static/src/xml/mrp_stage_dashboard.xml',
        ],
    },
    'images': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
}
